# Generated by Django 2.1.2 on 2018-10-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20181001_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='followedby',
            name='user',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='passward',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Followedby',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='postedby',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ManyToManyField(through='instagram.PostedBy', to='instagram.User'),
        ),
    ]
