# Generated by Django 2.1.2 on 2018-10-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20181003_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='contrasena',
        ),
    ]
