# Generated by Django 2.1.2 on 2018-10-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20181003_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
