# Generated by Django 2.1.2 on 2018-10-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20181003_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likedby',
            name='like_id',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
